on: [push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: ["macos-13", "macos-latest", "windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libfido2-dev
      - name: Install dependencies (macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libfido2
      - name: Install scoop (windows)        
        if: matrix.os == 'windows-latest'
        uses: MinoruSekine/setup-scoop@main
      - name: Install dependencies (windows)        
        if: matrix.os == 'windows-latest'
        run: |
          scoop bucket add keys.pub https://github.com/keys-pub/scoop-bucket
          scoop install libfido2
          echo "$HOME/scoop/apps/libfido2/current" >> $GITHUB_PATH
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build
